In [7]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/3. Matrices/13. LL product")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [8]:
import numpy as np

def LL_product(L1, L2):
    # YOUR CODE HERE
    # n = L1.shape[0]
    # C = np.zeros((n, n))
    
    # for i in range(n):
    #     for j in range(i + 1):
    #         C[i, j] = np.dot(L1[i, :i + 1], L2[:i + 1, j])
    C = L1 * L2
    #print(C)
    return C

In [9]:
import time

start = time.time()

debug_result = [LL_product(**x) for x in debug_cases]
answer = [LL_product(**x) for x in public_cases]

print(time.time() - start, '<- Elapsed time')

[[-10   0   0   0   0   0   0]
 [  0  -8   0   0   0   0   0]
 [-16  -4   0   0   0   0   0]
 [  0  -3 -10  16   0   0   0]
 [  9  -3  -3  -6  -5   0   0]
 [ -3  20  -4  -9  12 -20   0]
 [ 16  -1 -16  -6   1   6  -6]]
[[-3  0]
 [ 0  3]]
[[3]]
[[4]]
[[-16   0   0   0   0   0   0]
 [  5  -4   0   0   0   0   0]
 [ 20 -12 -12   0   0   0   0]
 [ -2   3   2  25   0   0   0]
 [  4 -12   0   0   0   0   0]
 [  3  10   6 -12   8   0   0]
 [ -6  -2  10 -15 -20  -4   1]]
[[-5  0]
 [-9 -4]]
[[-15   0   0   0   0   0   0   0   0]
 [ -3  12   0   0   0   0   0   0   0]
 [  0   2  -8   0   0   0   0   0   0]
 [ 12  -4 -12   8   0   0   0   0   0]
 [  8  20  -1   0  -6   0   0   0   0]
 [-20   0   0  -2   0   0   0   0   0]
 [  4   4   1  -5  10   0   6   0   0]
 [-10  10   4   0   9 -15  -2  -6   0]
 [ -1 -12   5  -8   1   1 -15   3  20]]
[[0]]
[[-20   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0]
 [ 16   1   3   0   0   0   0   0]
 [-16   0  -1  -4   0   0   0   0]
 [ -3  12  15   