In [25]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/4. Linear Transforms/6. Change of basis")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [26]:
import numpy as np

def change_of_basis(B, x):
    # YOUR CODE HERE
    x_new = x @ np.linalg.inv(B)
    
    return x_new

In [27]:
import time

start = time.time()

debug_result = [change_of_basis(**x) for x in debug_cases]
answer = [change_of_basis(**x) for x in public_cases]

print(time.time() - start, '<- Elapsed time')

[-64778.          93658.99999999 -42108.          -7731.
  -3686.           -785.            461.        ]
[ -96594.00000256 -236799.00000628 -175791.00000466   42273.00000112
    8551.00000023   -5687.00000015    2407.00000006     491.00000001]
[-211477.99999788  -73414.99999926   12417.99999988   55792.99999944
   -4043.99999996   10710.99999989   13081.99999987    2931.99999997]
[-230768.00000225 -108540.00000106  -12741.00000012 -190020.00000185
  -35419.00000034   50039.00000049  -11445.00000011]
[-6.6808403e+07 -1.6738562e+07  4.1299760e+06  1.4020130e+06
 -4.1023700e+05  8.3408000e+04  1.9192000e+04  3.5950000e+03]
[ 350. -227.   99.]
[113.  22.   8.]
[51. -3. 10.  9.]
[-1.46623e+05 -1.91770e+04 -1.01030e+04 -3.37900e+03 -1.07800e+03
 -2.02000e+02  1.50000e+01]
[2415.  811. 1229. -463. -182.]
[105. -21.  -5.]
[ 286.  -33. -113.   20.   -7.]
[-36190.  -8625.  -4199.   -901.   -394.    105.]
[-6.14483e+05 -1.46871e+05 -3.19530e+04 -6.03600e+03  7.91000e+02
 -1.15700e+03 -3.44000e+